version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:z
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
    env_file:
      - ./api/.env
    restart: on-failure
  api:
    image: rest-api-cfg-files:1.0
    build: ./api
    ports:
      - "8888:8080"
    volumes:
      - ./api:/workdir:z
    restart: on-failure
    depends_on:
      - "db"
